### PR TITLE
Locale: Update fr_FR translations

### PR DESCRIPTION
**Pull request by pringles49**
Proposed changes in this pull-request:

- Adding grammar correction  	**7b4750a**
- Sorry 	**d9f6745**  and **7b4750a** Commit changes are  invert
- Adding missing keys to fr_FR.js 	**d9f6745**
- Adding more french traduction to **ce887b6**

---------------------------------------------------------------------------------------

> for ce887b6:

``` Before ( this is just a example there are  more change)```

before

```After ```
after
---------------------------------------------------------------------------------------
>  for d9f6745

```
Object.keys(OSjs.Locales.en_EN).filter(function(v) {
  return typeof OSjs.Locales.fr_FR[v] === 'undefined';
});
output ::
[]
```
---------------------------------------------------------------------------------------
#369

### CODE REVIEW

**Comment by andersevenrud** [comment]
It seems that some of the translations you added should have been in the *Application Locales*, not the *Core Locales*.

See: https://github.com/os-js/OS.js/blob/master/src/packages/default/Settings/locale.js

Mostly "labels" go in the global translation files (Like "LBL_FOO" or "ERROR_SOMETHING")

**Comment by andersevenrud** [comment]
Disregard my last comment (if you got it) -- I simply looked at the wrong thing! My mistake :)

Just a comment: You've made 5 commits -- really it should be *one*. This is mentioned in the contribution documentation.

I can squash the commits, but then you have to reset your repository to be able to get future updates.

**Comment by pringles49** [comment]
YOU SCARE ME 😄  !!!! ok i will reset my repository

**Comment by andersevenrud** [comment]
Don't reset until I have merged this though. Or else these changes are lost!

**Comment by andersevenrud** [comment]
Merged in: cf36e18963c09721b4ec6e6c7af6a275aed6898c
Your new commit: bca0be5c0a0e09fc90c685a700c2d1f6c9929e57

You can now reset your repo (or manually force updating it... if you know how :) )

**Pull request closed without merging**
