### PR TITLE
server-php: Improve exception handling and remove end closing tags

### PR DESCRIPTION
**Pull request by eduardor2k**
It's recommended to remove the end closing tag in php, if you don't need to send anything extra to the browser.

Missing exception thrown fixed

### CODE REVIEW

**Comment by andersevenrud** [comment]
Your commit still has the same message (pull-request title does not matter in this case).

Also, your branch has two merges that I cannot accept into my branch.


If you don't know how to rebase and squash (including changing the message), I'd advice making a backup of your changes, reset your fork completely and import the backup, then re-commit changes with the correct message.

untitled


I set up a couple of rules a while back regarding this, so I don't make a mess of the commit-history of this project (which leads to all sorts of trouble).


More information: https://os.js.org/doc/manuals/man-development.html

**Comment by eduardor2k** [comment]
Hi, sorry about that!

I will push everything once i follow the guidelines.

**Comment by andersevenrud** [comment]
No problem, mate! :)

**Comment by andersevenrud** [comment]
I realized I forgot to update the manual I linked -- I just fixed this (it was a broken link and missing text)

**Comment by andersevenrud** [comment]
(The old stuff is probably cached for a few minutes, so refresh a couple of times to get the updated manual)

**Comment by andersevenrud** [comment]
Need any help to get going ? :) Just asking because I did not get any new notifications

**Pull request closed without merging**
