### PR TITLE
remove null elements in windows-list

### PR DESCRIPTION
**Pull request by dreadkopp**
might not be the most performant and elegant solution though :P

Proposed changes in this pull-request:

-
-
-

---

*Please make sure that you read the guidelines and test your code before submission, or else your request might be rejected*

### CODE REVIEW

**Comment by andersevenrud** [comment]
If you look at https://github.com/os-js/OS.js/commit/5adb87ac3161c55e3700f1f1da87e8a02ec6804c (it's another branch btw, so style is not identical), I put this in the `getWindows` instead. So you might wanna reflect this change.

I actually don't remember why `.splice()` did not work out to well (which is basically what happens when you use the filter as in this PR), but I think it was something to do with pointers getting broken. Now, that might have been only for older browsers -- I'll have to investigate on that.

**Comment by dreadkopp** [comment]
ah, that's a much prettier filter :) however my installation does not support ES6 yet :/

**Comment by andersevenrud** [comment]
I was thinking that you'd change this PR to reflect the changes I made in the commit I showed you :)

**Comment by andersevenrud** [comment]
This was fixed in the `v2.1.0` release, so I'm closing this PR since it's no longer compatible with the codebase. Sadly you won't get any contrib stats on the change since this patch was not involved :(

**Pull request closed without merging**
