### PR TITLE
Display the font size correctly in Writer

### PR DESCRIPTION
**Pull request by iBluemind**
Hi Anders, again.

I found that the font size is displayed "NaN" in some case in Writer.

Check please :)
Thanks!

### CODE REVIEW

**Comment by andersevenrud** [comment]
You don't actually check if it is NaN :)

**Comment by iBluemind** [comment]
Umm.. But, content of the font size button display "NaN" in some case like the above screenshot.
I think it is not user friendly.. Is it really okay..?

**Comment by andersevenrud** [comment]
All I am saying is that, you wrote you check for NaN, which means `isNaN(number)` ;)

This works too of course

**Comment by iBluemind** [comment]
Aha, my bad, soory. I'll fix it :)

**Pull request merged**
