### PR TITLE
add japanese (Core)

### PR DESCRIPTION
**Pull request by fai1618**

### CODE REVIEW

**Comment by andersevenrud** [comment]
Nice!

I think some new translations was added after you cloned the repository. Can you take a look ? (I know it was about ZIP and some VFS stuff)

**Comment by fai1618** [comment]
oh,sorry.
I fix it right now

**Comment by drzix** [comment]
I think these commits need to be squashed :)

**Comment by fai1618** [comment]
I made a mistake so I closed this pull request.
I send pull request another branch.
I'm sorry.

**Pull request closed without merging**
