### PR TITLE
some updates to dutch translation

### PR DESCRIPTION
**Pull request by koter84**
i translated new sentences to the dutch language and made some minor changes to some existing translated strings.

### CODE REVIEW

**Comment by andersevenrud** [comment]
Cool!

I see you've already squashed your commits and doing some other changes -- would you mind changing your commit message to:

> Locale: Updated nl_NL (Dutch) translations

? :)

**Comment by koter84** [comment]
no problem, i'll change the commit message in a couple of minutes

**Comment by koter84** [comment]
it's ready to be merged

**Comment by andersevenrud** [comment]
There might be some missing translations in the apps as well (Like Settings). So if you want to you can have a look there too :)

**Comment by andersevenrud** [comment]
Thanks!

**Pull request merged**
