### PR TITLE
added missing it_IT locale, fixed existig ones

### PR DESCRIPTION
**Pull request by Kirkhammetz**
Following #18 it_IT locale update request

### CODE REVIEW

**Comment by marktopper** [comment]
Nice 👍

**Comment by andersevenrud** [comment]
Nice :)

There's quite a few new translation entries coming next week if you're interested ;)

**Comment by Kirkhammetz** [comment]
Sure I'll give them a look! 👍 

On a side note, I tried to get the missing ones through the object keys but the browser doesn't expose OSjs as global, it gave me undefined didn't have time to dig deeper, am I missing something?

**Comment by andersevenrud** [comment]
Just close and re-open the developer tools. Or reload the page with it open. Happens to me sometimes in Chrome for unknown reasons

**Comment by andersevenrud** [comment]
@Kirkhammetz I have made the update now -- so some stuff to update :)

**Comment by marktopper** [comment]
Locale `it_IT` misses:
```
 - LBL_BACK
 - LBL_ICON
 - LBL_UNINSTALL
 - LBL_REGENERATE
 - LBL_WINDOWMANAGER
 - LBL_HOTKEY
 - LBL_HOTKEYS
 - LBL_MOUNTS
 - LBL_ID
 - LBL_APPLICATION
 - LBL_SCOPE
 - LBL_REPOSITORY
 - LBL_PERSONAL
 - LBL_SYSTEM
 - LBL_STARTING
 - LBL_STORE
 - LBL_LOCALE
 - LBL_PACKAGE
 - LBL_INPUT
 - LBL_MISC
 - LBL_OTHER
 - LBL_USERS
 - LBL_FONTS
```

**Pull request merged**
