### PR TITLE
Locales translation it_IT Italian

### PR DESCRIPTION
**Pull request by Kirkhammetz**
Localization it_IT, italian language for core and packages

### CODE REVIEW

**Comment by andersevenrud** [comment]
PR #286 introduced some minor movment of locales in certain files.

Can you make sure your fork is up-to-date ? I cannot automatically merge it if it is not

**Comment by andersevenrud** [comment]
You might have to resolve some commits to make it work for you -- you know how ?

Follow these instructions on how to keep your fork up to date (in case you don-t know) https://robots.thoughtbot.com/keeping-a-github-fork-updated

:)

**Comment by eraffaelli** [comment]
Sorry I screw up all ^^'
FYI, I have included the it_IT translation in my PR as well with the reorder.

**Comment by andersevenrud** [comment]
Oh... I should have checked closer :P

Currently on the train on my way home from work and looked over quickly -- it looked OK.

Then I will close this :)

**Comment by andersevenrud** [comment]
So you speak Italian and French ?


Well deserved spot: https://github.com/os-js/OS.js/wiki/Hall-of-Fame

**Comment by eraffaelli** [comment]
Not really but to avoid conflict with this PR for my reorder, I have included @Kirkhammetz translation.

**Comment by andersevenrud** [comment]
Now I'm confused. Which parts did you do ?

**Comment by eraffaelli** [comment]
FR only. I've added the IT translation of this PR in mine because I was working on reorder when this PR come up.
Sorry for the confusion :/

**Comment by andersevenrud** [comment]
Then @Kirkhammetz won't get a spot in Github contributors... Oh well..

At least he got mentioned here https://github.com/os-js/OS.js/wiki/Hall-of-Fame

Thanks @Kirkhammetz !

**Comment by eraffaelli** [comment]
Sorry :/

**Comment by Kirkhammetz** [comment]
Ehi don't worry no problem, I'm glad to help, let me know if there are some new packages/core to translate :)

**Comment by andersevenrud** [comment]
@Kirkhammetz There is definately more coming up! I have you on my list now :)

**Comment by andersevenrud** [comment]
Crap. I just *now* noticed that the Italian translations were never merged here Oo

**Comment by andersevenrud** [comment]
@Kirkhammetz Is it possible for you to make a new pull-request with these translations ? They were'nt merged after all -- something went very wrong here! :P 

Then you'll be included in the contribution list after all!

There's been some additions to the locales, so look out for that!

**Comment by Kirkhammetz** [comment]
@andersevenrud Sure! I'm going to give it a look this weekend

**Comment by andersevenrud** [comment]
@Kirkhammetz Awesome! :)

Then I will close this one

**Pull request closed without merging**
