### PR TITLE
Added french fr_fr translation

### PR DESCRIPTION
**Pull request by eraffaelli**
Added french fr_fr translation and reorder language by alphabetical order for simpler organization.
Also added some missing "es_ES" string in package.json files where localisation were in locales.js files.
Also added the italian translation actually in PR.

For the es_ES added string I put english because I don't know which spanish word fit the best.

Tell me if it's too much and you want multiple PR or if the reordering is too much (I'm new to community project and git so I don't know if you want more splitting).

### CODE REVIEW

**Comment by eraffaelli** [comment]
Sorry, I just read again the translation note and see...
> Simply fill out the objects in top of file

**Comment by drzix** [comment]
I think it's good to reorder the list of languages like this. When I translated, so confused was where I should insert my language into the list.

**Comment by andersevenrud** [comment]
> Added french fr_fr translation and reorder language by alphabetical order for simpler organization.

Not a bad idea :)

Thanks @eraffaelli 

> I think it's good to reorder the list of languages like this. When I translated, so confused was where I should insert my language into the list.

@drzix Generally it does not matter :)

**Comment by eraffaelli** [comment]
You're welcome ;)

**Pull request merged**
