### PR TITLE
Update vi_VN.js

### PR DESCRIPTION
**Pull request by J2TeaM**
Proposed changes in this pull-request:

- Update some words in the translation.

### CODE REVIEW

**Comment by khoaakt** [comment]
:)

**Comment by andersevenrud** [comment]
Cool! :)

I have no way to validate this as I do not speak this language.

@khoaakt @drzix Comments ?

**Comment by khoaakt** [comment]
@andersevenrud This pull so perfect! Agree!

**Comment by andersevenrud** [comment]
Thanks! :)

**Pull request merged**
