### PR TITLE
Docker database install

### PR DESCRIPTION
**Pull request by jbourdale**
Proposed changes in this pull-request:

- Enhanced Dockerfile to support database storage and auth
- Adding docker_start.sh script that configure osjs
- Adding docker environnement variables names used in docker_start.sh to INSTALL.md
---

*Please make sure that you read the guidelines and test your code before submission, or else your request might be rejected*

### CODE REVIEW

**Comment by andersevenrud** [comment]
Wow, this is great stuff! I'll have a look a bit later today :)

**Comment by jbourdale** [comment]
@andersevenrud feel free to check !

**Comment by jbourdale** [comment]
I updated as you ask.
If you want, you can push the dockerfile to the docker hub then remove "docker build -t [YOUR TAG] ." and change "docker run -p 8000:8000 [YOUR_TAG]" to "docker run -p 8000:8000 osjs/osjs"

**Comment by andersevenrud** [comment]
Great! I'll merge this tomorrow when I am back home at my workstation :)I

**Pull request merged**
