### PR TITLE
Fix minor grammatical error in README

### PR DESCRIPTION
**Pull request by mathiscode**
"without checkout out" -> "without checking out"

### CODE REVIEW

**Comment by andersevenrud** [comment]
Thanks!

If you want to change the manual, this is also repeated here:

https://github.com/os-js/manual.os-js.org/tree/master/src/v3/install#demo

**Comment by mathiscode** [comment]
I'll get right on it! 😄

**Comment by RossComputerGuy** [comment]
That part of the manual doesn't look like a grammar error.

**Comment by RossComputerGuy** [comment]
Right now that says "Or check out the official v3 online demo". It sounds weird when you change it to "Or checking out the official v3 online demo" so it would have to be "Or by checking out the official v3 online demo".

**Comment by mathiscode** [comment]
> 
> 
> Right now that says "Or check out the official v3 online demo". It sounds weird when you change it to "Or checking out the official v3 online demo" so it would have to be "Or by checking out the official v3 online demo".

The part that is changed is ["without checkout out" to "without checking out"](https://github.com/os-js/OS.js/pull/740/files).

**Comment by RossComputerGuy** [comment]
Oh, I didn't see that line.

**Comment by andersevenrud** [comment]
I probably intended to write "You can run a demo using Docker without checkout of any source-code", but this is just as good :)

**Pull request merged**
