### PR TITLE
Update vi_VN

### PR DESCRIPTION
**Pull request by khoaakt**
Proposed changes in this pull-request:

- Update vi_VN in the translation.

### CODE REVIEW

**Comment by andersevenrud** [comment]
@khoaakt There's actually more left. See #18 on how to find out what :)

**Comment by khoaakt** [comment]
@andersevenrud Done :)

**Comment by andersevenrud** [comment]
FYI: If you make your commits in the `master` branch, you'll have to reset your repository every time you make a pull request. You should probably do everything in a custom branch :)

https://os.js.org/doc/manuals/man-development.html#section-contribute

**Comment by andersevenrud** [comment]
:)

**Pull request merged**
