### PR TITLE
Use absolute path

### PR DESCRIPTION
**Pull request by marktopper**
Use absolute path for better server support.

### CODE REVIEW

**Comment by andersevenrud** [comment]
This actually has no effect. It will always look up relative to the current directory of given source file if the path does not start with `/` (or `LETTER:\` for windows).

`require(__DIR__ . 'foo`)` is the same as `require('foo')`  :)

**Comment by marktopper** [comment]
Without `__DIR__` it uses the relative path from the indexed PHP-file.

Which means that if the indexed PHP-file is `api.php`, then it will workout fine.
But if that is not the case it will use a wrong path.

I noticed this since that I use a PHP based service ([Valet](https://laravel.com/docs/master/valet)) to handle local domains (like http://osjs.dev) which I use for development.
In this case the indexed PHP-file is inside Valet, and then it requires the `api.php`-file if the uri matches.

If you wanna test it out yourself, you can install Valet and then add my [`OsjsValetDriver.php`](https://gist.github.com/marktopper/311b2cb001407740605757c447d69882#file-osjsvaletdriver-php) to Valet.

**Comment by andersevenrud** [comment]
@marktopper Aha. There's probably some other weird cases with PHP :)

Are there any more paths like this in the codebase?

The entire PHP server could use a rewrite, really. It was more of a prototype than anything else

**Comment by marktopper** [comment]
I will look through an see if there are other cases like this.

Will be back.

**Comment by marktopper** [comment]
@andersevenrud: It doesn't seems to be a case anywhere else.

**Pull request merged**
