### PR TITLE
New it_IT attempt

### PR DESCRIPTION
**Pull request by Kirkhammetz**
My first PR of it_IT locals + #289 issue followup, updated to current master branch, conflicts resolved.

grunt jscs jshint return no errors, but I see travis it's not going well, I never used it in my workflow so let me know if there is something I shoud check.

### CODE REVIEW

**Comment by andersevenrud** [comment]
Looks good to me! :) The failing test is because of an utdated package referenced in `package.json` (I will fix that myself)

Could you please squash your commits to something like "Added it_IT locales" or something ?

https://github.com/os-js/OS.js/blob/master/CONTRIBUTING.md#making-and-submitting-changes

**Comment by andersevenrud** [comment]
I can squash it myself, just checking if you know how :)

**Comment by Kirkhammetz** [comment]
I didn't know, I'm checking how to for the time :)

**Comment by andersevenrud** [comment]
I just tried it for myself, and it's not that easy since one of your commits are made in the past and conflicts occur while doing a `git rebase`.

I think the best option here is to make a backup of your translations, reset your repo, then copy changed files back and do a new commit and PR.

The `npm-debug.log` should not be in the commit btw :)

**Comment by Kirkhammetz** [comment]
I was thinking of resetting a couple of hour ago because of it, let's close this pr then, I'll make the reset when I have some spare time in the next days :)

**Comment by andersevenrud** [comment]
Allright :)

**Comment by andersevenrud** [comment]
Just wondering about the status here. Not in a hurry or anything, just like to keep myself updated :)

**Comment by Kirkhammetz** [comment]
Yea I know sorry, I've been really busy at work, I'm going to take sometimes tonight to do it or it'll take forever!

**Comment by andersevenrud** [comment]
> Yea I know sorry, I've been really busy at work, I'm going to take sometimes tonight to do it or it'll take forever!

Don't feel sorry, man. It's not like you even had to do this, but I really appreciate that you did :)

**Pull request closed without merging**
