### PR TITLE
Window: not allow window to resize top of the window over panel

### PR DESCRIPTION
**Pull request by drzix**
Like moving, resizing also should limit the top size

Signed-off-by: drzix <korea.drzix@gmail.com>

### CODE REVIEW

**Comment by andersevenrud** [comment]
Hmm. There is something wrong with my style check task.. some things does not get caught :/

Can you please change it to this ?

```
      if ( newTop <= current.rectWorkspace.top && newTop !== null ) {
         newTop = current.rectWorkspace.top;
         newHeight -= current.rectWorkspace.top - mousePosition.y;
       }
 
```

Other then that, really nice work!

**Comment by drzix** [comment]
I changed it. Good night!

**Comment by andersevenrud** [comment]
You forgot to push ? :)

Good night!

**Comment by drzix** [comment]
Hmm..? I used "commit --amend" and "push -f".
To me, the code in this PR is already changed to changed one

**Comment by andersevenrud** [comment]
You're still missing a space before closing your if statement

```
      if ( newTop <= current.rectWorkspace.top && newTop !== null ) {  // <- HERE
         newTop = current.rectWorkspace.top;
         newHeight -= current.rectWorkspace.top - mousePosition.y;
       }

```

**Comment by andersevenrud** [comment]
Nice :) Now, get to bed! hehe.

**Comment by drzix** [comment]
Omg... really sorry.
Now, really good night :)

**Pull request merged**
