### PR TITLE
Updated FileManager fr_FR locales following #289.

### PR DESCRIPTION
**Pull request by eraffaelli**

### CODE REVIEW

**Comment by andersevenrud** [comment]
:)

**Comment by iBluemind** [comment]
Please add the new translation in Draw application, too!
Check these following two lines in src/packages/default/Draw/locales.js:322,323!

https://github.com/os-js/OS.js/commit/6da763ea20746410f83c4ab68ad6182b68ece5e5#diff-87da43c131304836e3d6cf51626587c2R322

**Comment by andersevenrud** [comment]
Huh ? Me ?

**Comment by iBluemind** [comment]
@andersevenrud No, I told @eraffaelli..! I'm sorry :)

He added the new translation(by #289) in FileManager, but there is no the one in Draw.
So I want to notify him.

**Comment by andersevenrud** [comment]
Ah :)

**Pull request merged**
