### PR TITLE
Missing "new Exception"

### PR DESCRIPTION
**Pull request by eduardor2k**
server-php: Updated exception handling in handler template

### CODE REVIEW

**Comment by andersevenrud** [comment]
Could you please change the commit message to `server-php: Updated exception handling in handler template`, or something like that ?

**Comment by andersevenrud** [comment]
Also, your repository is from `30 Dec 2015`, which is very, very old. Please update it to upstream, or I will be unable to merge your requests

https://help.github.com/articles/syncing-a-fork/

**Comment by eduardor2k** [comment]
Hi, I've already updated my fork & updated the comment

**Comment by eduardor2k** [comment]
Please dismiss this push request

**Pull request closed without merging**
