### PR TITLE
Fully automate dev setup with Gitpod

### PR DESCRIPTION
**Pull request by Kori-Syusetu**
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitLab, GitHub, and Bitbucket that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

### CODE REVIEW

**Comment by Kori-Syusetu** [comment]
Sorry. this is miss

**Comment by andersevenrud** [comment]
What do you mean by "miss" ? :)

**Comment by Kori-Syusetu** [comment]
"I forked the repository, but I accidentally tried to reflect the GitPod settings in the original repository." This is what I call "Miss".
**Original Text**
「私はリポジトリをフォークしましたが、GitPodの設定先を誤って元のリポジトリに反映させようとした。」これが私の言う"Miss"です

**Comment by andersevenrud** [comment]
Aha! I understand.

**Pull request closed without merging**
